name: Docker Publish

on:
  push:
    branches:
      - main
    paths:
      - 'images/**'

env:
  CONTEXT: .

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [docker-compose, uv, just, bat, bottom, bpftop, dust, eza, sd, kyanos]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0

      - name: Login to registry
        uses: docker/login-action@v3.3.0
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push ${{ matrix.service }}
        uses: docker/build-push-action@v6.10.0
        with:
          context: ${{ env.CONTEXT }}
          platforms: linux/amd64
          file: images/${{ matrix.service }}.Dockerfile
          push: true
          cache-from: type=registry,ref=docker.io/lvillis/${{ matrix.service }}:latest
          cache-to: type=inline
          tags: docker.io/lvillis/${{ matrix.service }}:latest
